services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=dnd_user
      - POSTGRES_PASSWORD=dnd_password
      - POSTGRES_DB=dnd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app/back
      - ./front:/app/front
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://dnd_user:dnd_password@db:5432/dnd_db
    depends_on:
      - db

volumes:
  postgres_data:
